name: AccumulationPosts

on:
  workflow_dispatch :
    inputs:
      date:
        description: 'date yyyy/MM/dd'
        required: false
        default: ''
      next:
        description: 'next yyyy/MM/dd'
        required: false
        default: ''
      general:
        description: 'general'
        required: false
        default: ''
  # schedule:
  #   - cron: "45 03 4,14,24 * *" # */4,14,24 12:45
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run
      run: > 
        dotnet run --
        --command ${{ github.workflow }}
        --twitter-api-key ${{ secrets.TWITTER_API_KEY }}
        --twitter-api-secret ${{ secrets.TWITTER_API_SECRET }}
        --bearer-token ${{ secrets.BEARER_TOKEN }}
        --access-token ${{ secrets.ACCESS_TOKEN }}
        --access-token-secret ${{ secrets.ACCESS_TOKEN_SECRET }}
        --google-service-account-jwt ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JWT }}
        --date ${{ github.event.inputs.date }}
        --next ${{ github.event.inputs.next }}
        --general ${{ github.event.inputs.general }}
    - name: Git
      run: |
        git status
        git diff
        git add -A
        git config --local user.email "example.com"
        git config --local user.name "bot"
        git commit -m "auto commit"
        git pull --no-rebase
        git push
