name: NotificationMorning

on:
  workflow_dispatch :
  schedule:
    - cron: "30 00 3,13,23 * *" # */3,13,23 09:30

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run
      run: > 
        dotnet run --
        --command ${{ github.workflow }}
        --twitter-api-key ${{ secrets.TWITTER_API_KEY }}
        --twitter-api-secret ${{ secrets.TWITTER_API_SECRET }}
        --bearer-token ${{ secrets.BEARER_TOKEN }}
        --access-token ${{ secrets.ACCESS_TOKEN }}
        --access-token-secret ${{ secrets.ACCESS_TOKEN_SECRET }}
        --google-service-account-jwt ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JWT }}
        